#comenten los casos que no quieran testear.
python programas/programa1.py entradas/entrada1.txt salidas/programa1_entrada1.txt
python programas/programa1.py entradas/entrada2.txt salidas/programa1_entrada2.txt
python programas/programa1.py entradas/entrada3.txt salidas/programa1_entrada3.txt
python programas/programa1.py entradas/entrada4.txt salidas/programa1_entrada4.txt
python programas/programa1.py entradas/entrada5.txt salidas/programa1_entrada5.txt
python programas/programa2.py entradas/entrada1.txt salidas/programa2_entrada1.txt
python programas/programa2.py entradas/entrada2.txt salidas/programa2_entrada2.txt
python programas/programa2.py entradas/entrada3.txt salidas/programa2_entrada3.txt
python programas/programa2.py entradas/entrada4.txt salidas/programa2_entrada4.txt
python programas/programa2.py entradas/entrada5.txt salidas/programa2_entrada5.txt
python programas/programa3.py entradas/entrada1.txt salidas/programa3_entrada1.txt
python programas/programa3.py entradas/entrada2.txt salidas/programa3_entrada2.txt
python programas/programa3.py entradas/entrada3.txt salidas/programa3_entrada3.txt
python programas/programa3.py entradas/entrada4.txt salidas/programa3_entrada4.txt
python programas/programa3.py entradas/entrada5.txt salidas/programa3_entrada5.txt
python programas/programa4.py entradas/entrada1.txt salidas/programa4_entrada1.txt
python programas/programa4.py entradas/entrada2.txt salidas/programa4_entrada2.txt
python programas/programa4.py entradas/entrada3.txt salidas/programa4_entrada3.txt
python programas/programa4.py entradas/entrada4.txt salidas/programa4_entrada4.txt
python programas/programa4.py entradas/entrada5.txt salidas/programa4_entrada5.txt
python programas/programa5.py entradas/entrada1.txt salidas/programa5_entrada1.txt
python programas/programa5.py entradas/entrada2.txt salidas/programa5_entrada2.txt
python programas/programa5.py entradas/entrada3.txt salidas/programa5_entrada3.txt
python programas/programa5.py entradas/entrada4.txt salidas/programa5_entrada4.txt
python programas/programa5.py entradas/entrada5.txt salidas/programa5_entrada5.txt